[package]
name = "ockam_abac"
version = "0.56.0"
authors = ["Ockam Developers"]
categories = ["cryptography", "authorization"]
edition = "2021"
homepage = "https://github.com/build-trust/ockam"
keywords = ["ockam", "crypto", "encryption", "authorization"]
license = "Apache-2.0"
publish = true
readme = "README.md"
repository = "https://github.com/build-trust/ockam/tree/develop/implementations/rust/ockam/ockam_abac"
description = "Attribute based authorization control"

[features]
default = ["std"]
no_std = ["ockam_core/no_std", "ockam_identity/no_std", "ockam_executor"]
alloc = ["ockam_core/alloc", "ockam_identity/alloc"]
repl = ["rustyline", "rustyline-derive", "std"]
std = [
  "ockam_core/std",
  "ockam_identity/std",
  "ockam_node/std",
  "minicbor/std",
  "tracing/std",
  "either/use_std",
  "once_cell/std",
  "sqlx",
  "regex",
  "tokio",
  "wast",
  "strum/std",
  "serde/std",
]

[dependencies]
cfg-if = "1.0.0"
either = { workspace = true }
minicbor = { workspace = true, default-features = true, features = ["derive", "alloc"] }
ockam_core = { version = "0.108.0", path = "../ockam_core", default-features = false }
ockam_identity = { version = "0.110.0", path = "../ockam_identity", default-features = false }
ockam_node = { version = "0.115.0", path = "../ockam_node", default-features = false }
once_cell = { workspace = true, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }

# optional:
ockam_executor = { version = "0.77.0", path = "../ockam_executor", default-features = false, optional = true }
regex = { workspace = true, default-features = false, optional = true }
rusqlite = { workspace = true, optional = true }
rustyline = { workspace = true, optional = true }
rustyline-derive = { workspace = true, optional = true }
sqlx = { workspace = true, optional = true }
str-buf = { workspace = true }
tokio = { workspace = true, default-features = false, optional = true, features = ["sync", "time", "rt", "rt-multi-thread", "macros"] }
tracing = { workspace = true, default-features = false, features = ["attributes"] }
wast = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", default-features = false, features = ["rust-crypto"] }
quickcheck = { workspace = true }
rand = { workspace = true }
tempfile = { workspace = true }

[[bin]]
name = "repl"
test = true
required-features = ["repl"]
path = "src/bin/repl.rs"
