logger:
  level: ALL
  format: logfmt
  add_timestamp: false
  static_fields:
    '@service': benthos

input:
  ockam_kafka:
    topics: [topic_A]
    consumer_group: example_group
    disable_content_encryption: true
    ockam_allow: kafka-outlet
    ockam_enrollment_ticket: ${OCKAM_ENROLLMENT_TICKET}
    ockam_route_to_kafka_outlet: /project/default/service/forward_to_redpanda/secure/api

pipeline:
  processors:
    - bloblang: |
        root = this
        root.data.message = this.data.message.uppercase()

output:
  sql_insert:
    driver: snowflake
    dsn: "${SNOWFLAKE_HOST}:${SNOWFLAKE_PORT}/${SNOWFLAKE_DATABASE}/${SNOWFLAKE_SCHEMA}?authenticator=OAUTH&account=${SNOWFLAKE_ACCOUNT}&token=${SNOWFLAKE_TOKEN}&warehouse=${SNOWFLAKE_WAREHOUSE}"
    table: KAFKA_MESSAGES
    columns: [ ID, EMAIL, MESSAGE ]
    args_mapping: |
      root = [
        meta("kafka_offset"),
        data.email,
        this.data.message
      ]